version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      PGDATA: /data/postgres
      POSTGRES_DB: server
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
